version: 2

sources:
  - name: olist_raw
    database: dsai-module-2-project-496708
    schema: olist_raw
    tables:
      - name: orders
      - name: order_items
      - name: customers
      - name: products
      - name: sellers
      - name: payments
      - name: reviews
      - name: geolocation
      - name: category_translation